[application]

asset_dir = "assets"
default_platform = "web"

[web.app]

# HTML title tag content
title = "dioxus-test-app1"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = [
]

# Additional JavaScript files
script = [
]

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[web.watcher]
reload_html = true
